// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OrderItemFormController from "./order_item_form_controller"
application.register("order-item-form", OrderItemFormController)

import QuantityInputController from "./quantity_input_controller"
application.register("quantity-input", QuantityInputController)
