meta_name: "Nou ration"
meta_title: "Nou ration. Pas kit to sofa! Pass to command."
meta_description: "Pas kit to sofa! Pass to command. Online supermarket delivery 30 minutes. Mauritius"
meta_image: "logo.png" # should exist in `app/assets/images/`
